name: insurance_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  lucide_icons: ^0.257.0
  provider: ^6.1.5+1
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/health_plans.json
    - assets/data/auto_plans.json
    - assets/data/term_plans.json
    - assets/data/plan_details.json
    - assets/ins1.jpg
    - assets/ins2.jpg
    - assets/ins3.png
