name: insurance_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
<<<<<<< HEAD
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  lucide_icons: ^0.257.0
  provider: ^6.1.5+1
  equatable: ^2.0.8
=======
  google_fonts: ^7.0.1
  flutter_animate: ^4.5.2
  lucide_icons: ^0.257.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  http: ^1.6.0
>>>>>>> 439ddb8cea7c8238ea1b458e68168840ccc34272

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
<<<<<<< HEAD
    - assets/data/health_plans.json
    - assets/data/auto_plans.json
    - assets/data/term_plans.json
    - assets/data/plan_details.json
    - assets/ins1.jpg
    - assets/ins2.jpg
    - assets/ins3.png
=======
>>>>>>> 439ddb8cea7c8238ea1b458e68168840ccc34272
